version: 1
update_configs:
  - package_manager: "go:modules"
    directory: "/"
    update_schedule: "daily"
    commit_message:
      prefix: "[MISC] "
      include_scope: true
  - package_manager: "javascript"
    directory: "/web"
    update_schedule: "live"
    commit_message:
      prefix: "[MISC] "
      include_scope: true